spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fintrack?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: fintrack
    password: fintrack
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info